development:
  adapter: postgresql
  encodeing: unicode
  host: db
  database: twitter_management
  username: postgres
  pool: 20
  timeout: 15000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
